### ISSUE TITLE
metrics.py中计算NDCG与MAP的相关问题

### ISSUE THREAD

**Issue by ke-01** [myx666/LeCaRD#13]
您好，想问一下计算NDCG的时候，现在是用返回的前n个结果计算，且N是全局最优的30个答案从高到低排列计算DCG的值，但是MAP计算的时候为什么是只考虑有标签全局最优的30个元素的排序作为ranks，而不是用全部元素的排序作为ranks呢?

**Comment by zuochao912** [comment]
请问您是否验证了ndcg的指标呢，我也觉得有些奇怪

**Comment by brick-pid** [comment]
同问，请问你解决这个问题了吗？ @ke-01
